# Generated by Django 3.1.7 on 2021-04-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=6000)),
                ('answer', models.CharField(max_length=10000)),
                ('test_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluatorApp.test')),
            ],
        ),
    ]
